#!/usr/bin/env bash
# Runs legacy_expected.dart on 3.x's protobuf runtime (docs/modules/M5.4-douyin.md).
#
# 3.x decoded Douyin frames with classes generated by protoc_plugin on
# package:protobuf 6.1.0 and fixnum 1.1.x. Neither is a workspace dependency,
# so this builds a throwaway package from the pub cache (offline) with 3.x's
# generated files from archive/v4, runs the generator against this
# repository and removes the package again.
#
#   bash fixtures/douyin/danmaku/legacy_expected.sh
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

mkdir -p "$work/bin/proto"
cp "$root/fixtures/douyin/danmaku/legacy_expected.dart" "$work/bin/"
for file in douyin.pb.dart douyin.pbenum.dart; do
  git -C "$root" show "archive/v4:legacy/lib/core/danmaku/proto/$file" >"$work/bin/proto/$file"
done
cat >"$work/pubspec.yaml" <<'EOF'
name: douyin_legacy_expected
publish_to: none
environment:
  sdk: ^3.13.0
dependencies:
  protobuf: 6.1.0
  fixnum: ^1.1.0
EOF

(cd "$work" && dart pub get --offline >/dev/null)
dart --packages="$work/.dart_tool/package_config.json" "$work/bin/legacy_expected.dart" "$root"
