#!/usr/bin/env python3
"""Generates the Android TV banners (spec/design/principles.md §3.1, §3.2).

320×180 at xhdpi (a 160×90 dp vector, so every density is sharp): brand night
blue, the TV mark of the launcher icon in white with the play triangle cut
out, and the wordmark beside it, a quarter of the mark's height apart. The
wordmark is set in Noto Sans CJK SC Bold (SIL OFL 1.1) and converted to
outlines here, so no font ships with the app.

    python3 apps/pure_live/tool/tv_banner.py          # write the drawables
    python3 apps/pure_live/tool/tv_banner.py --check  # fail when they are stale

Needs fontTools and the Noto Sans CJK collection (`fonts-noto-cjk`).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTCollection

FONT = Path('/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc')
FONT_INDEX = 2  # Noto Sans CJK SC
RES = Path(__file__).resolve().parent.parent / 'android/app/src/main/res'
OUTPUTS = {
    RES / 'drawable/tv_banner.xml': '纯粹直播',
    RES / 'drawable-en/tv_banner.xml': 'Pure Live',
}

NIGHT_BLUE = '#FF0B1B3F'
WHITE = '#FFFFFFFF'
WIDTH, HEIGHT = 320, 180
MARK_HEIGHT = 76.0  # the TV mark, antennas included
TEXT_SIZE = 46.0  # font size of the wordmark in banner pixels
MARGIN = 20.0

# The TV of ic_launcher_foreground.xml (108 viewport): antennas, screen and the
# play triangle, spanning x 30–78 and y 27.4–75 once the round caps count.
MARK_BOX = (30.0, 27.4, 78.0, 75.0)


def fmt(value: float) -> str:
    text = f'{value:.1f}'
    return text[:-2] if text.endswith('.0') else text


def mark_paths(scale: float, dx: float, dy: float) -> list[tuple[str, str]]:
    def p(x: float, y: float) -> str:
        return f'{fmt(x * scale + dx)},{fmt(y * scale + dy)}'

    r = 6 * scale
    screen = (
        f'M{p(36, 38)} L{p(72, 38)} A{fmt(r)},{fmt(r)} 0 0 1 {p(78, 44)} L{p(78, 69)} '
        f'A{fmt(r)},{fmt(r)} 0 0 1 {p(72, 75)} L{p(36, 75)} A{fmt(r)},{fmt(r)} 0 0 1 {p(30, 69)} '
        f'L{p(30, 44)} A{fmt(r)},{fmt(r)} 0 0 1 {p(36, 38)} Z'
    )
    triangle = f'M{p(49, 48.5)} L{p(63, 56.5)} L{p(49, 64.5)} Z'
    return [
        ('antennas', f'M{p(47, 37)} L{p(40, 29)} M{p(61, 37)} L{p(68, 29)}'),
        ('screen', screen),
        ('triangle', triangle),
    ]


def wordmark(text: str, size: float) -> tuple[str, float, float, float]:
    """Outline path of [text] at [size] with its origin on the baseline; returns
    the path, its advance width and the ink's top and bottom (y down)."""
    font = TTCollection(str(FONT)).fonts[FONT_INDEX]
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    scale = size / font['head'].unitsPerEm
    pen = SVGPathPen(glyphs, ntos=fmt)
    measure = BoundsPen(glyphs)
    x = 0.0
    for char in text:
        glyph = glyphs[cmap[ord(char)]]
        # Flip y: font units grow upwards, the drawable's grow downwards.
        transform = (scale, 0, 0, -scale, x, 0)
        glyph.draw(TransformPen(pen, transform))
        glyph.draw(TransformPen(measure, transform))
        x += glyph.width * scale
    _, top, _, bottom = measure.bounds
    return pen.getCommands(), x, top, bottom


def banner(text: str) -> str:
    mark_w = MARK_BOX[2] - MARK_BOX[0]
    mark_h = MARK_BOX[3] - MARK_BOX[1]
    mark_scale = MARK_HEIGHT / mark_h
    gap = MARK_HEIGHT / 4  # principles §3.2: a quarter of the mark's height
    path, advance, top, bottom = wordmark(text, TEXT_SIZE)
    total = mark_w * mark_scale + gap + advance
    fit = min(1.0, (WIDTH - 2 * MARGIN) / total)
    left = (WIDTH - total * fit) / 2
    mark_dx = left - MARK_BOX[0] * mark_scale * fit
    mark_dy = (HEIGHT - MARK_HEIGHT * fit) / 2 - MARK_BOX[1] * mark_scale * fit
    text_x = left + (mark_w * mark_scale + gap) * fit
    # The wordmark's ink is centred on the mark's screen.
    screen_mid = mark_dy + (38 + 75) / 2 * mark_scale * fit
    text_y = screen_mid - (top + bottom) / 2 * fit
    mark = mark_paths(mark_scale * fit, mark_dx, mark_dy)
    stroke = fmt(3.2 * mark_scale * fit)
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Android TV banner, spec/design/principles.md §3.1: 320×180 at xhdpi. Generated by',
        '     apps/pure_live/tool/tv_banner.py from the launcher mark and Noto Sans CJK SC Bold',
        '     (SIL OFL 1.1) outlines; do not edit by hand. -->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="160dp"',
        '    android:height="90dp"',
        f'    android:viewportWidth="{WIDTH}"',
        f'    android:viewportHeight="{HEIGHT}">',
        '    <path',
        f'        android:fillColor="{NIGHT_BLUE}"',
        f'        android:pathData="M0,0 H{WIDTH} V{HEIGHT} H0 Z" />',
        '    <path',
        f'        android:strokeColor="{WHITE}"',
        f'        android:strokeWidth="{stroke}"',
        '        android:strokeLineCap="round"',
        f'        android:pathData="{mark[0][1]}" />',
        '    <path',
        f'        android:fillColor="{WHITE}"',
        f'        android:pathData="{mark[1][1]}" />',
        '    <path',
        f'        android:fillColor="{NIGHT_BLUE}"',
        f'        android:pathData="{mark[2][1]}" />',
        '    <group',
        f'        android:translateX="{fmt(text_x)}"',
        f'        android:translateY="{fmt(text_y)}"',
        f'        android:scaleX="{fit:.4f}"',
        f'        android:scaleY="{fit:.4f}">',
        '        <path',
        f'            android:fillColor="{WHITE}"',
        f'            android:pathData="{path}" />',
        '    </group>',
        '</vector>',
        '',
    ]
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true', help='fail when a drawable differs')
    args = parser.parse_args()
    stale = []
    for output, text in OUTPUTS.items():
        content = banner(text)
        if args.check:
            if not output.exists() or output.read_text(encoding='utf-8') != content:
                stale.append(str(output))
            continue
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding='utf-8')
        print(f'wrote {output} ({len(content)} bytes)')
    if stale:
        print('stale: ' + ', '.join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
