// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rooms,
    follows,
    followAreas,
    tags,
    roomTags,
    history,
    blockRules,
    roomPrefs,
    settings,
    meta,
    iptvPlaylists,
    iptvChannels,
    iptvGuideSources,
    iptvGuideChannels,
    iptvProgrammes,
    iptvChannelsName,
    iptvChannelsGroup,
    iptvProgrammesChannel,
    iptvProgrammesStop,
  ];
  late final Shape0 rooms = Shape0(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(platform, room_id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 follows = Shape1(
    source: i0.VersionedTable(
      entityName: 'follows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(room)'],
      columns: [_column_17, _column_18, _column_19, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 followAreas = Shape2(
    source: i0.VersionedTable(
      entityName: 'follow_areas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(platform, namespace, area_id)'],
      columns: [
        _column_0,
        _column_1,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 tags = Shape3(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_27, _column_28, _column_29, _column_30, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 roomTags = Shape4(
    source: i0.VersionedTable(
      entityName: 'room_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(room, tag)'],
      columns: [_column_17, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 history = Shape5(
    source: i0.VersionedTable(
      entityName: 'history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 blockRules = Shape6(
    source: i0.VersionedTable(
      entityName: 'block_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(kind, value_folded)'],
      columns: [_column_0, _column_34, _column_35, _column_36, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 roomPrefs = Shape7(
    source: i0.VersionedTable(
      entityName: 'room_prefs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(room, "key")'],
      columns: [_column_17, _column_38, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 settings = Shape8(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_38, _column_35, _column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 meta = Shape9(
    source: i0.VersionedTable(
      entityName: 'meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_38, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 iptvPlaylists = Shape10(
    source: i0.VersionedTable(
      entityName: 'iptv_playlists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_28,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_18,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 iptvChannels = Shape11(
    source: i0.VersionedTable(
      entityName: 'iptv_channels',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_46,
        _column_47,
        _column_28,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 iptvGuideSources = Shape12(
    source: i0.VersionedTable(
      entityName: 'iptv_guide_sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_28,
        _column_39,
        _column_41,
        _column_58,
        _column_43,
        _column_44,
        _column_45,
        _column_18,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 iptvGuideChannels = Shape13(
    source: i0.VersionedTable(
      entityName: 'iptv_guide_channels',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(source, channel_id)'],
      columns: [_column_59, _column_60, _column_61, _column_62],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 iptvProgrammes = Shape14(
    source: i0.VersionedTable(
      entityName: 'iptv_programmes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_59,
        _column_60,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index iptvChannelsName = i1.Index(
    'iptv_channels_name',
    'CREATE INDEX iptv_channels_name ON iptv_channels (name)',
  );
  final i1.Index iptvChannelsGroup = i1.Index(
    'iptv_channels_group',
    'CREATE INDEX iptv_channels_group ON iptv_channels (playlist, group_name, position)',
  );
  final i1.Index iptvProgrammesChannel = i1.Index(
    'iptv_programmes_channel',
    'CREATE INDEX iptv_programmes_channel ON iptv_programmes (source, channel_id, start)',
  );
  final i1.Index iptvProgrammesStop = i1.Index(
    'iptv_programmes_stop',
    'CREATE INDEX iptv_programmes_stop ON iptv_programmes (stop)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get platform =>
      columnsByName['platform']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get roomId =>
      columnsByName['room_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nick =>
      columnsByName['nick']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get avatar =>
      columnsByName['avatar']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cover =>
      columnsByName['cover']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get area =>
      columnsByName['area']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get onlineViewers =>
      columnsByName['online_viewers']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get popularity =>
      columnsByName['popularity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalViewers =>
      columnsByName['total_viewers']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get followers =>
      columnsByName['followers']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastStatus =>
      columnsByName['last_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastLiveAt =>
      columnsByName['last_live_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get extra =>
      columnsByName['extra']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'platform',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'room_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nick',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'avatar',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'area',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'online_viewers',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'popularity',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_viewers',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'followers',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_live_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'extra',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get room =>
      columnsByName['room']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get followedAt =>
      columnsByName['followed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'room',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES rooms(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'followed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'user\'',
      defaultValue: const i1.CustomExpression('\'user\''),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get platform =>
      columnsByName['platform']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get namespace =>
      columnsByName['namespace']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get areaId =>
      columnsByName['area_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get areaName =>
      columnsByName['area_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get typeName =>
      columnsByName['type_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get areaPic =>
      columnsByName['area_pic']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get shortName =>
      columnsByName['short_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'namespace',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'area_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'area_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'area_pic',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'short_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameFolded =>
      columnsByName['name_folded']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name_folded',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get room =>
      columnsByName['room']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get tag =>
      columnsByName['tag']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES tags(id)ON DELETE CASCADE',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get room =>
      columnsByName['room']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastWatchedAt =>
      columnsByName['last_watched_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'room',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL UNIQUE REFERENCES rooms(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_watched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get valueFolded =>
      columnsByName['value_folded']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value_folded',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get room =>
      columnsByName['room']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userAgent =>
      columnsByName['user_agent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get autoSync =>
      columnsByName['auto_sync']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get guideUrl =>
      columnsByName['guide_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastSyncAt =>
      columnsByName['last_sync_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAttemptAt =>
      columnsByName['last_attempt_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_agent',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'auto_sync',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (auto_sync IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'guide_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_sync_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_attempt_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playlist =>
      columnsByName['playlist']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupName =>
      columnsByName['group_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tvgId =>
      columnsByName['tvg_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tvgName =>
      columnsByName['tvg_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get logo =>
      columnsByName['logo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catchupMode =>
      columnsByName['catchup_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catchupSource =>
      columnsByName['catchup_source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get catchupDays =>
      columnsByName['catchup_days']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get catchupCorrection =>
      columnsByName['catchup_correction']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get headers =>
      columnsByName['headers']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'playlist',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES iptv_playlists(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tvg_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tvg_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'logo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'catchup_mode',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'catchup_source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_55(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'catchup_days',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_56(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'catchup_correction',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'headers',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get autoSync =>
      columnsByName['auto_sync']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get selected =>
      columnsByName['selected']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSyncAt =>
      columnsByName['last_sync_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAttemptAt =>
      columnsByName['last_attempt_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'selected',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (selected IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get source =>
      columnsByName['source']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get channelId =>
      columnsByName['channel_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get names =>
      columnsByName['names']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES iptv_guide_sources(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'channel_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'names',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get source =>
      columnsByName['source']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get channelId =>
      columnsByName['channel_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get start =>
      columnsByName['start']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get stop =>
      columnsByName['stop']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subtitle =>
      columnsByName['subtitle']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catchupId =>
      columnsByName['catchup_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stop',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'subtitle',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'catchup_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rooms,
    follows,
    followAreas,
    tags,
    roomTags,
    history,
    blockRules,
    roomPrefs,
    settings,
    meta,
    iptvPlaylists,
    iptvChannels,
    iptvGuideSources,
    iptvGuideChannels,
    iptvProgrammes,
    searchHistory,
    iptvChannelsName,
    iptvChannelsGroup,
    iptvProgrammesChannel,
    iptvProgrammesStop,
  ];
  late final Shape0 rooms = Shape0(
    source: i0.VersionedTable(
      entityName: 'rooms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(platform, room_id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 follows = Shape1(
    source: i0.VersionedTable(
      entityName: 'follows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(room)'],
      columns: [_column_17, _column_18, _column_19, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 followAreas = Shape2(
    source: i0.VersionedTable(
      entityName: 'follow_areas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(platform, namespace, area_id)'],
      columns: [
        _column_0,
        _column_1,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 tags = Shape3(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_27, _column_28, _column_29, _column_30, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 roomTags = Shape4(
    source: i0.VersionedTable(
      entityName: 'room_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(room, tag)'],
      columns: [_column_17, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 history = Shape5(
    source: i0.VersionedTable(
      entityName: 'history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 blockRules = Shape6(
    source: i0.VersionedTable(
      entityName: 'block_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(kind, value_folded)'],
      columns: [_column_0, _column_34, _column_35, _column_36, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 roomPrefs = Shape7(
    source: i0.VersionedTable(
      entityName: 'room_prefs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(room, "key")'],
      columns: [_column_17, _column_38, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 settings = Shape8(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_38, _column_35, _column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 meta = Shape9(
    source: i0.VersionedTable(
      entityName: 'meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_38, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 iptvPlaylists = Shape10(
    source: i0.VersionedTable(
      entityName: 'iptv_playlists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_28,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_18,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 iptvChannels = Shape11(
    source: i0.VersionedTable(
      entityName: 'iptv_channels',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_46,
        _column_47,
        _column_28,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 iptvGuideSources = Shape12(
    source: i0.VersionedTable(
      entityName: 'iptv_guide_sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_28,
        _column_39,
        _column_41,
        _column_58,
        _column_43,
        _column_44,
        _column_45,
        _column_18,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 iptvGuideChannels = Shape13(
    source: i0.VersionedTable(
      entityName: 'iptv_guide_channels',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(source, channel_id)'],
      columns: [_column_59, _column_60, _column_61, _column_62],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 iptvProgrammes = Shape14(
    source: i0.VersionedTable(
      entityName: 'iptv_programmes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_59,
        _column_60,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 searchHistory = Shape15(
    source: i0.VersionedTable(
      entityName: 'search_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(keyword_folded)'],
      columns: [_column_69, _column_70, _column_71],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index iptvChannelsName = i1.Index(
    'iptv_channels_name',
    'CREATE INDEX iptv_channels_name ON iptv_channels (name)',
  );
  final i1.Index iptvChannelsGroup = i1.Index(
    'iptv_channels_group',
    'CREATE INDEX iptv_channels_group ON iptv_channels (playlist, group_name, position)',
  );
  final i1.Index iptvProgrammesChannel = i1.Index(
    'iptv_programmes_channel',
    'CREATE INDEX iptv_programmes_channel ON iptv_programmes (source, channel_id, start)',
  );
  final i1.Index iptvProgrammesStop = i1.Index(
    'iptv_programmes_stop',
    'CREATE INDEX iptv_programmes_stop ON iptv_programmes (stop)',
  );
}

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get keywordFolded =>
      columnsByName['keyword_folded']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get keyword =>
      columnsByName['keyword']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get searchedAt =>
      columnsByName['searched_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'keyword_folded',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'keyword',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_71(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'searched_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
