/// The loading styles' names (3.x `AppConsts.allStyles`): key → (Chinese,
/// English).
const Map<String, (String, String)> loadingStyleNames = {
  'default': ('默认圆环', 'Default Ring'),
  'rotatingPlain': ('旋转方块', 'Rotating Plain'),
  'doubleBounce': ('双重大圆', 'Double Bounce'),
  'wave': ('波浪跳跃', 'Wave'),
  'wanderingCubes': ('双块漫游', 'Wandering Cubes'),
  'fadingFour': ('交替隐藏', 'Fading Four'),
  'fadingCube': ('渐隐方块', 'Fading Cube'),
  'pulse': ('脉冲水波', 'Pulse'),
  'chasingDots': ('追逐双圆', 'Chasing Dots'),
  'threeBounce': ('三点弹跳', 'Three Bounce'),
  'circle': ('时钟小点', 'Circle'),
  'cubeGrid': ('九宫方格', 'Cube Grid'),
  'fadingCircle': ('渐隐圆圈', 'Fading Circle'),
  'rotatingCircle': ('旋转大圆', 'Rotating Circle'),
  'foldingCube': ('折叠魔方', 'Folding Cube'),
  'pumpingHeart': ('心跳波动', 'Pumping Heart'),
  'hourGlass': ('翻转沙漏', 'Hour Glass'),
  'pouringHourGlass': ('流动沙漏', 'Pouring Hour Glass'),
  'pouringHourGlassRefined': ('质感沙漏', 'Hour Glass Refined'),
  'fadingGrid': ('矩阵渐隐', 'Fading Grid'),
  'ring': ('纯净圆环', 'Ring'),
  'ripple': ('震荡涟漪', 'Ripple'),
  'spinningCircle': ('半圆飞旋', 'Spinning Circle'),
  'spinningLines': ('流动线条', 'Spinning Lines'),
  'squareCircle': ('方变圆弧', 'Square Circle'),
  'dualRing': ('双轨游环', 'Dual Ring'),
  'pianoWave': ('琴键节奏', 'Piano Wave'),
  'dancingSquare': ('律动方块', 'Dancing Square'),
  'threeInOut': ('三点缩放', 'Three In Out'),
  'waveSpinner': ('声波雷达', 'Wave Spinner'),
  'pulsingGrid': ('脉冲网格', 'Pulsing Grid'),
  'waveDots': ('律动圆点', 'Wave Dots'),
  'inkDrop': ('动态水滴', 'Ink Drop'),
  'twistingDots': ('基因螺旋', 'Twisting Dots'),
  'threeRotatingDots': ('三星环绕', 'Three Rotating'),
  'staggeredDotsWave': ('错落波浪', 'Staggered Wave'),
  'fourRotatingDots': ('四星环绕', 'Four Rotating'),
  'fallingDot': ('重力落点', 'Falling Dot'),
  'progressiveDots': ('线性生长', 'Progressive Dots'),
  'discreteCircular': ('分离圆环', 'Discrete Circle'),
  'threeArchedCircle': ('三重连环', 'Three Arched'),
  'bouncingBall': ('地面弹球', 'Bouncing Ball'),
  'flickr': ('环绕互换', 'Flickr'),
  'hexagonDots': ('六角矩阵', 'Hexagon Dots'),
  'beat': ('心率电波', 'Beat'),
  'twoRotatingArc': ('双轴弧旋', 'Two Rotating Arc'),
  'horizontalRotatingDots': ('水平环绕', 'Horizontal Dots'),
  'newtonCradle': ('牛顿摆球', 'Newton Cradle'),
  'stretchedDots': ('拉伸光点', 'Stretched Dots'),
  'halfTriangleDot': ('三角错落', 'Half Triangle'),
  'dotsTriangle': ('动态三角', 'Dots Triangle'),
  'ballPulse': ('三点渐变', 'Ball Pulse'),
  'ballGridPulse': ('九宫格闪烁', 'Ball Grid Pulse'),
  'ballClipRotate': ('裁剪圆环旋转', 'Ball Clip Rotate'),
  'ballClipRotatePulse': ('双层环球旋转', 'Ball Clip Rotate Pulse'),
  'squareSpin': ('方块翻转', 'Square Spin'),
  'ballClipRotateMultiple': ('多重碎片圆环', 'Ball Clip Rotate Multiple'),
  'ballPulseRise': ('交错交替上升', 'Ball Pulse Rise'),
  'ballRotate': ('三球围绕旋转', 'Ball Rotate'),
  'cubeTransition': ('双对角方块位移', 'Cube Transition'),
  'ballZigZag': ('双球Z字错位', 'Ball ZigZag'),
  'ballZigZagDeflect': ('双球曲线反弹', 'Ball ZigZag Deflect'),
  'ballTrianglePath': ('三角轨迹循环', 'Ball Triangle Path'),
  'ballTrianglePathColored': ('三角彩轨循环', 'Ball Triangle Path Colored'),
  'ballTrianglePathColoredFilled': ('三角实心循环', 'Ball Triangle Filled'),
  'ballScale': ('单圆水波脉冲', 'Ball Scale'),
  'lineScale': ('五线谱律动', 'Line Scale'),
  'lineScaleParty': ('律动线条', 'Line Scale Party'),
  'ballScaleMultiple': ('多重水波涟漪', 'Ball Scale Multiple'),
  'ballPulseSync': ('三点波浪同步', 'Ball Pulse Sync'),
  'ballBeat': ('三点心跳缩放', 'Ball Beat'),
  'lineScalePulseOut': ('线条由内向外扩散', 'Line Scale Pulse Out'),
  'lineScalePulseOutRapid': ('线条高频向外扩散', 'Line Scale Pulse Out Rapid'),
  'ballScaleRipple': ('空心圆环震荡', 'Ball Scale Ripple'),
  'ballScaleRippleMultiple': ('多重空心涟漪', 'Ball Scale Ripple Multiple'),
  'ballSpinFadeLoader': ('经典菊花圆点', 'Ball Spin Fade Loader'),
  'lineSpinFadeLoader': ('经典时钟线条', 'Line Spin Fade Loader'),
  'triangleSkewSpin': ('三角倾斜翻转', 'Triangle Skew Spin'),
  'pacman': ('吃豆人游戏', 'Pacman'),
  'ballGridBeat': ('九宫格心跳闪烁', 'Ball Grid Beat'),
  'semiCircleSpin': ('半圆飞速旋转', 'Semi Circle Spin'),
  'ballRotateChase': ('圆点接力追逐', 'Ball Rotate Chase'),
  'orbit': ('行星轨道公转', 'Orbit'),
  'audioEqualizer': ('音频均衡器', 'Audio Equalizer'),
  'circleStrokeSpin': ('纯净描边圆环', 'Circle Stroke Spin'),
};
