"""Generates packages/live_net/lib/src/codec/brotli_dictionary.dart.

The Brotli static dictionary (122,784 bytes) is taken from the hexadecimal
dump in RFC 7932 Appendix A and checked against the length and CRC-32 the RFC
states for it. With --check-lib the bytes are also compared with the
dictionary compiled into the local libbrotlicommon (the reference
implementation). The SHA-256 printed at the end is the value
packages/live_net/test/brotli_test.dart pins.

    python3 tools/brotli/gen_dictionary.py [--rfc rfc7932.txt] [--check-lib]

Without --rfc the RFC is downloaded from www.rfc-editor.org. Standard library
only.
"""
import argparse
import base64
import ctypes
import ctypes.util
import hashlib
import re
import sys
import urllib.request
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'packages/live_net/lib/src/codec/brotli_dictionary.dart'
RFC_URL = 'https://www.rfc-editor.org/rfc/rfc7932.txt'

# Stated in RFC 7932 Appendix A.
DICTIONARY_LENGTH = 122784
DICTIONARY_CRC32 = 0x5136CB04

# Base64 characters per source line; with the indentation and quotes the lines
# stay within the formatter's 120 columns.
CHUNK = 112


def read_rfc(path):
    if path:
        return Path(path).read_text(encoding='utf-8')
    with urllib.request.urlopen(RFC_URL, timeout=60) as response:
        return response.read().decode('utf-8')


def dictionary_from_rfc(text):
    start = text.index('Appendix A.  Static Dictionary Data')
    end = text.index('The number of words for each length', start)
    hex_lines = re.findall(r'^ {6}([0-9a-f]+)$', text[start:end], re.M)
    data = bytes.fromhex(''.join(hex_lines))
    if len(data) != DICTIONARY_LENGTH:
        sys.exit(f'dictionary length {len(data)}, RFC 7932 states {DICTIONARY_LENGTH}')
    crc = zlib.crc32(data)
    if crc != DICTIONARY_CRC32:
        sys.exit(f'dictionary CRC-32 {crc:#010x}, RFC 7932 states {DICTIONARY_CRC32:#010x}')
    return data


class BrotliDictionary(ctypes.Structure):
    _fields_ = [
        ('size_bits_by_length', ctypes.c_uint8 * 32),
        ('offsets_by_length', ctypes.c_uint32 * 32),
        ('data_size', ctypes.c_size_t),
        ('data', ctypes.POINTER(ctypes.c_uint8)),
    ]


def dictionary_from_library():
    name = ctypes.util.find_library('brotlicommon')
    if not name:
        sys.exit('--check-lib: libbrotlicommon not found')
    library = ctypes.CDLL(name)
    library.BrotliGetDictionary.restype = ctypes.POINTER(BrotliDictionary)
    dictionary = library.BrotliGetDictionary().contents
    return ctypes.string_at(dictionary.data, dictionary.data_size)


def dart_source(data, sha256):
    encoded = base64.b64encode(data).decode('ascii')
    lines = [f"  '{encoded[i:i + CHUNK]}'" for i in range(0, len(encoded), CHUNK)]
    lines[-1] += ','
    return '\n'.join([
        '// GENERATED by tools/brotli/gen_dictionary.py from RFC 7932 Appendix A. Do not edit.',
        '//',
        f'// {len(data)} bytes, CRC-32 {zlib.crc32(data):#010x} (as stated in the RFC),',
        f'// SHA-256 {sha256}.',
        '',
        "import 'dart:convert';",
        "import 'dart:typed_data';",
        '',
        '/// The Brotli static dictionary (RFC 7932 section 8 and Appendix A), decoded',
        '/// on first use.',
        'final Uint8List brotliDictionary = base64Decode(',
        *lines,
        ');',
        '',
    ])


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--rfc', help='local copy of rfc7932.txt (default: download it)')
    parser.add_argument('--check-lib', action='store_true', help='compare with the local libbrotlicommon')
    args = parser.parse_args()

    data = dictionary_from_rfc(read_rfc(args.rfc))
    sha256 = hashlib.sha256(data).hexdigest()
    if args.check_lib:
        library = dictionary_from_library()
        if library != data:
            sys.exit('libbrotlicommon dictionary differs from RFC 7932 Appendix A')
        print('libbrotlicommon: identical')
    OUTPUT.write_text(dart_source(data, sha256), encoding='utf-8')
    print(f'{OUTPUT.relative_to(ROOT)}: {len(data)} bytes, CRC-32 {zlib.crc32(data):#010x}, SHA-256 {sha256}')


if __name__ == '__main__':
    main()
