// ignore_for_file: constant_identifier_names (the glyph names of 3.x)

import 'package:flutter/widgets.dart';

/// The app's own icon font (3.x `CustomIcons`, assets/icons/CustomIcons.ttf).
///
/// Generated by FlutterIcon.com from Fontello. Glyphs from Font Awesome 4 and
/// 5, Copyright (C) 2016 by Dave Gandy, SIL Open Font License
/// (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt).
abstract final class CustomIcons {
  static const _family = 'CustomIcons';
  static const _package = 'live_ui';

  /// Danmaku off.
  static const IconData danmaku_close = IconData(0xe800, fontFamily: _family, fontPackage: _package);

  /// Danmaku on.
  static const IconData danmaku_open = IconData(0xe801, fontFamily: _family, fontPackage: _package);

  /// Danmaku settings.
  static const IconData danmaku_setting = IconData(0xe802, fontFamily: _family, fontPackage: _package);

  /// Popular (the 热门 tab).
  static const IconData popular = IconData(0xe803, fontFamily: _family, fontPackage: _package);

  /// Search.
  static const IconData search = IconData(0xe804, fontFamily: _family, fontPackage: _package);

  /// QQ.
  static const IconData qq_1 = IconData(0xe805, fontFamily: _family, fontPackage: _package);

  /// Floating window (picture-in-picture).
  static const IconData float_window = IconData(0xe806, fontFamily: _family, fontPackage: _package);

  /// Cast.
  static const IconData cast = IconData(0xe807, fontFamily: _family, fontPackage: _package);

  /// GitHub.
  static const IconData github_circled = IconData(0xf09b, fontFamily: _family, fontPackage: _package);

  /// Mail.
  static const IconData mail_squared = IconData(0xf199, fontFamily: _family, fontPackage: _package);

  /// WeChat.
  static const IconData wechat = IconData(0xf1d7, fontFamily: _family, fontPackage: _package);

  /// Telegram.
  static const IconData telegram = IconData(0xf2c6, fontFamily: _family, fontPackage: _package);

  /// Alipay.
  static const IconData alipay = IconData(0xf642, fontFamily: _family, fontPackage: _package);
}
