// Generated by `dart run drift_dev make-migrations`, then adapted: pure-Dart
// `package:test`, and the v1 → v2 data test filled in.
import 'package:drift/drift.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:live_store/src/database/database.dart';
import 'package:test/test.dart';

import 'generated/schema.dart';
import 'generated/schema_v1.dart' as v1;
import 'generated/schema_v2.dart' as v2;

void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  late SchemaVerifier verifier;

  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  group('simple database migrations', () {
    // Every schema step, without data: the migrated schema must equal the
    // dumped one.
    const versions = GeneratedHelper.versions;
    for (final (i, fromVersion) in versions.indexed) {
      group('from $fromVersion', () {
        for (final toVersion in versions.skip(i + 1)) {
          test('to $toVersion', () async {
            final schema = await verifier.schemaAt(fromVersion);
            final db = StoreDatabase(schema.newConnection());
            await verifier.migrateAndValidate(db, toVersion);
            await db.close();
          });
        }
      });
    }
  });

  test('migration from v1 to v2 keeps every v1 row and adds empty IPTV tables', () async {
    const room = v1.RoomsData(
      id: 1,
      platform: 'douyu',
      roomId: '5526219',
      nick: '主播',
      title: '标题',
      extra: '{"notice":"公告"}',
      updatedAt: 1790467200000,
    );
    const follow = v1.FollowsData(room: 1, sortOrder: 0, followedAt: 1790467200000, source: 'user');
    const tag = v1.TagsData(id: 't1', name: '常看', nameFolded: '常看', description: '', sortOrder: 0);
    const roomTag = v1.RoomTagsData(room: 1, tag: 't1');
    const history = v1.HistoryData(id: 1, room: 1, lastWatchedAt: 1790467200000);
    const setting = v1.SettingsData(key: 'danmaku.speed', value: '120', updatedAt: 1790467200000);
    const meta = v1.MetaData(key: 'device.lanId', value: 'android-1');

    await verifier.testWithDataIntegrity(
      oldVersion: 1,
      newVersion: 2,
      createOld: v1.DatabaseAtV1.new,
      createNew: v2.DatabaseAtV2.new,
      openTestedDatabase: StoreDatabase.new,
      createItems: (batch, oldDb) {
        batch
          ..insert(oldDb.rooms, room)
          ..insert(oldDb.follows, follow)
          ..insert(oldDb.tags, tag)
          ..insert(oldDb.roomTags, roomTag)
          ..insert(oldDb.history, history)
          ..insert(oldDb.settings, setting)
          ..insert(oldDb.meta, meta);
      },
      validateItems: (newDb) async {
        final rooms = await newDb.select(newDb.rooms).get();
        expect(
          [for (final r in rooms) (r.id, r.platform, r.roomId, r.nick, r.extra)],
          [(1, 'douyu', '5526219', '主播', '{"notice":"公告"}')],
        );
        expect((await newDb.select(newDb.follows).get()).single.followedAt, 1790467200000);
        expect((await newDb.select(newDb.tags).get()).single.name, '常看');
        expect((await newDb.select(newDb.roomTags).get()).single.tag, 't1');
        expect((await newDb.select(newDb.history).get()).single.lastWatchedAt, 1790467200000);
        expect((await newDb.select(newDb.settings).get()).single.value, '120');
        expect((await newDb.select(newDb.meta).get()).single.value, 'android-1');
        expect(await newDb.select(newDb.iptvPlaylists).get(), isEmpty);
        expect(await newDb.select(newDb.iptvChannels).get(), isEmpty);
        expect(await newDb.select(newDb.iptvGuideSources).get(), isEmpty);
        expect(await newDb.select(newDb.iptvGuideChannels).get(), isEmpty);
        expect(await newDb.select(newDb.iptvProgrammes).get(), isEmpty);
        // The new tables take rows, and deleting a playlist cascades.
        await newDb
            .into(newDb.iptvPlaylists)
            .insert(
              const v2.IptvPlaylistsData(
                id: 1,
                name: '列表',
                source: 'https://fixture/list.m3u',
                autoSync: 1,
                sortOrder: 0,
                createdAt: 1790467200000,
              ),
            );
        await newDb
            .into(newDb.iptvChannels)
            .insert(
              const v2.IptvChannelsData(
                id: 1,
                playlist: 1,
                position: 0,
                name: 'CCTV-1',
                groupName: '央视',
                url: 'https://fixture/1.m3u8',
              ),
            );
        await newDb.customStatement('PRAGMA foreign_keys = ON');
        await newDb.delete(newDb.iptvPlaylists).go();
        expect(await newDb.select(newDb.iptvChannels).get(), isEmpty);
      },
    );
  });
}
