targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            store: lib/src/database/database.dart
          schema_dir: drift_schemas/
          test_dir: test/drift/
          store_date_time_values_as_text: false
          named_parameters: true
          generate_manager: false
